config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/billadmin', as: 'rails_admin'
  resources :bills

  resources :users
  root to: 'public#rootpage'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin'             => 'sessions#new', :as => :signin
  get '/signout'            => 'sessions#destroy', :as => :signout
  get '/auth/failure'       => 'sessions#failure'

  get 'dashboard'           => 'app#dashboard', :as => :dashboard
  get 'trending'            => 'app#trending', :as => :trending
  
  get 'restaurants'         => 'app#comingsoon', :as => :restaurants
  get 'foodlanes'           => 'app#comingsoon', :as => :foodlanes
  get 'big_orders'          => 'app#comingsoon', :as => :big_orders
  get 'preferences'         => 'app#comingsoon', :as => :preferences
  get 'foodlane_help'       => 'app#comingsoon', :as => :foodlane_help
  

  post '/order/:rest_name/handle_order'       => 'app#handle_order', :as => :order_handler
  patch '/order/:rest_name/confirm'       => 'app#confirm', :as => :order_confirmer
  get '/order/:rest_name'                     => 'app#place_order', :as => :order_page

end

app/models/bill.rb
class Bill < ActiveRecord::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:club, :cart, :type, :email, :sms, :html)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :club %>
    <%= f.input :cart %>
    <%= f.input :type %>
    <%= f.input :email %>
    <%= f.input :sms %>
    <%= f.input :html %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <thead>
    <tr>
      <th>Club</th>
      <th>Cart</th>
      <th>Type</th>
      <th>Email</th>
      <th>Sms</th>
      <th>Html</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.club %></td>
        <td><%= bill.cart %></td>
        <td><%= bill.type %></td>
        <td><%= bill.email %></td>
        <td><%= bill.sms %></td>
        <td><%= bill.html %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Club:</strong>
  <%= @bill.club %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @bill.cart %>
</p>

<p>
  <strong>Type:</strong>
  <%= @bill.type %>
</p>

<p>
  <strong>Email:</strong>
  <%= @bill.email %>
</p>

<p>
  <strong>Sms:</strong>
  <%= @bill.sms %>
</p>

<p>
  <strong>Html:</strong>
  <%= @bill.html %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>