config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/billadmin', as: 'rails_admin'
  resources :bills

  resources :users
  root to: 'public#rootpage'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin'             => 'sessions#new', :as => :signin
  get '/signout'            => 'sessions#destroy', :as => :signout
  get '/auth/failure'       => 'sessions#failure'

  get 'dashboard'           => 'app#dashboard', :as => :dashboard
  get 'trending'            => 'app#trending', :as => :trending
  
  get 'restaurants'         => 'app#comingsoon', :as => :restaurants
  get 'foodlanes'           => 'app#comingsoon', :as => :foodlanes
  get 'big_orders'          => 'app#comingsoon', :as => :big_orders
  get 'preferences'         => 'app#comingsoon', :as => :preferences
  get 'foodlane_help'       => 'app#comingsoon', :as => :foodlane_help
  

  post '/order/:rest_name/handle_order'       => 'app#handle_order', :as => :order_handler
  patch '/order/:rest_name/confirm'       => 'app#confirm', :as => :order_confirmer
  get '/order/:rest_name'                     => 'app#place_order', :as => :order_page

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/app.html.erb
<% logged_in_requirement = true %>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= Applingo.get("meta-description")%>">
    <meta name="author" content="<%= Applingo.get("meta-author")%>">
    <meta name="keyword" content="<%= Applingo.get("search-tags")%>" >

    <title><%= Applingo.get('dashboard-titlebar-heading')%></title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="/assets/js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="/assets/lineicons/style.css">    
    <!-- <link rel="stylesheet" type="text/css" href="/assets/jquery.mobile-1.4.5.min.css">  -->
    <!-- Custom styles for this template -->
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/css/style-responsive.css" rel="stylesheet">
    <script src="/assets/js/jquery-1.8.3.min.js"></script>

    <%# javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- animes -->
      
    <!-- anime end -->
  </head>

  <body>
 <!-- class="sidebar-closed" -->
  <section id="container" class="sidebar-closed">
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
            <!--logo start-->
            <a href="/" class="logo">
              <b><%# Applingo.get('logo')%></b>
              <img src="/icon.png">
            </a>
            <!--logo end-->
            <% if logged_in_requirement %>
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="/">
                            My Foodlanes
                            <i class="fa fa-tasks"></i>
                            <span class="badge bg-theme">
                              <%= current_user.get_active_carts_percent_status.count %>
                            </span>
                        </a>
                        <ul class="dropdown-menu extended tasks-bar">
                            <div class="notify-arrow notify-arrow-green"></div>
                            <li>
                                <p class="green"><%= Applingo.get('navbar-collaborate-status')%></p>
                            </li>
                            <% current_user.get_active_carts_percent_status.each do |c| %>
                            <li>
                                <a href="/club/<%= c[:club] %>">
                                    <div class="task-info">
                                        <div class="desc"><%= c[:name] %></div>
                                        <div class="percent"><%= c[:percent] %>%</div>
                                    </div>
                                    <div class="progress progress-striped">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= c[:percent] %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= c[:percent] %>%">
                                            <span class="sr-only"><%= c[:percent] %>% Complete (success)</span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <% end %>
                            <!-- <li class="external">
                                <a href="#">See All Tasks</a>
                            </li> -->
                        </ul>
                    </li>

                    <!-- settings end -->
                    <!-- inbox dropdown start-->
                    <li id="header_inbox_bar" class="dropdown" style="margin-left:20px">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            Notifications
                            <i class="fa fa-envelope-o"></i>
                            <span class="badge bg-theme"><%= current_user.clubchats.count %></span>
                        </a>
                        <ul class="dropdown-menu extended inbox">
                            <div class="notify-arrow notify-arrow-green"></div>
                            <li>.</li>
                            <!-- <li>
                                <p class="green">You have <%= current_user.clubchats.count %> new messages</p>
                            </li> -->
                            <% current_user.clubchats.last(5).reverse.each do |cc| %> 
                            <li>
                                <!-- <a href="/track/1"> -->
                                    <span class="photo"><img alt="avatar" src="<%= cc.cart.restaurant.photo_url %>" style="max-width:40px;max-height:40px;"></span>
                                    <!-- <span class="subject">
                                    <span class="from"><%= cc.cart.restaurant.name %></span>
                                    <span class="time">Just now</span> -->
                                    </span>
                                    <span class="message">
                                        <%= cc.message %>
                                    </span>
                                <!-- </a> -->
                            </li>
                            <% end %>
                            <!-- <li>
                                <a href="index.html#">See all messages</a>
                            </li> -->
                        </ul>
                    </li>
                    <!-- inbox dropdown end -->
                </ul>
                <!--  notification end -->
            </div>
            <% end %>
            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><a class="logout" href="/signout">Logout</a></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside></aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
      <div class="container">
        <%= yield %>
        </div>
      </section>

      <!--main content end-->
     
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <!-- // <script src="/assets/js/jquery.js"></script> -->

    <script src="/assets/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/assets/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/assets/js/jquery.scrollTo.min.js"></script>
    <script src="/assets/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.sparkline.js"></script>


    <!--common script for all pages-->
    <script src="/assets/js/common-scripts.js"></script>
    
    <script type="text/javascript" src="/assets/js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="/assets/js/gritter-conf.js"></script>

    <!--script for this page-->
  <!--
  <script src="/assets/js/sparkline-chart.js"></script>    
	<script src="/assets/js/zabuto_calendar.js"></script>	
		-->
    <script type="text/javascript">
        $( document ).ready(function() {
            // if ($('#sidebar > ul').is(":visible") === true) {
            //     $('#main-content').css({
            //         'margin-left': '0px'
            //     });
            //     $('#sidebar').css({
            //         'margin-left': '-210px'
            //     });
            //     $('#sidebar > ul').hide();
            //     $("#container").addClass("sidebar-closed");
            // } else {
            //     $('#main-content').css({
            //         'margin-left': '210px'
            //     });
            //     $('#sidebar > ul').show();
            //     $('#sidebar').css({
            //         'margin-left': '0'
            //     });
            //     $("#container").removeClass("sidebar-closed");
            // }
            function update(element){
              if(element.innerHTML == "") return;
                a = element.innerHTML.split(":");
                mins = parseInt(a[0]);
                secs = parseInt(a[1])-1;
                if(secs<0){
                  if(mins>0){
                    mins -= 1;
                  }
                  else{
                    // console.log(element)
                    // console.log($(element).parent().parent()[0].id);
                    // pid = $(element).parent().parent().parent()[0].id;
                    // if(pid!= undefined)
                    // $("#"+pid).load(location.href + " #"+pid);
                    return;
                  }
                  secs = 59;
                }
                element.innerHTML = mins+":"+secs;
                // console.log(mins);
                // console.log(secs);
                return;
            }
            var interval = setInterval(function() {
              // timers = document.getElementsByClassName('timer_div');
              timers = $('.timer_div');
              for (var i=0; i<timers.length; i++) {
                  update(timers[i]);
              }
            }, 1000);

            console.log( "hey Geek, we would love to have you work with us than hacking around here. Contact magus12141@iiitd.ac.in :)  " );
        });
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foodlane" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Foodlane" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= Applingo.get("meta-description")%>">
    <meta name="author" content="<%= Applingo.get("meta-author")%>">
    <meta name="keyword" content="<%= Applingo.get("search-tags")%>" >

    <title><%= Applingo.get('dashboard-titlebar-heading')%></title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        
    <!-- Custom styles for this template -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/style-responsive.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/zocial.css" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  <div id="login-page"  >
	  	<div class="container">
	  		<div class="row" style="margin-top:50px">
	  			<div class="col-md-4" style="opacity:0.7">
	  				<img src="/images/pg2.jpg" width="100%">
	  			</div>
	  			<div class="col-md-4">
	  				<img src="/images/pg1.png" width="100%" style="height:400px;opacity:0.7">
	  				<a href="/signin" class="zocial googleplus">Sign in with Google Account</a>
	  			</div>
	  			<div class="col-md-4" style="opacity:0.7">
	  				<img src="/images/pg3.png" width="100%">
	  			</div>
	  		</div>
		            	
	  	
	  	</div>
	  </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="assets/js/jquery.backstretch.min.js"></script>
    <script>
        // $.backstretch("assets/img/login-bg.jpg", {speed: 500});
        // $.backstretch("/images/16-deserts-gilakids-full.jpg", {speed: 500});
        $.backstretch("/images/slide_321041_3006870_free.jpg", {speed: 500});
    </script>


  </body>
</html>